StratedgemeMonitor/Controllers/Alerts/AlertsController.cs
using Capital.GSG.FX.Data.Core.WebApi;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StratedgemeMonitor.Models.Alerts;
using StratedgemeMonitor.Models.Systems;
using StratedgemeMonitor.ViewModels.Alerts;
using System;
using System.Threading.Tasks;

namespace StratedgemeMonitor.Controllers.Alerts
{
    [Authorize]
    public class AlertsController : Controller
    {
        private readonly AlertsControllerUtils utils;

        public AlertsController(AlertsControllerUtils utils)
        {
            this.utils = utils;
        }

        public IActionResult Index(DateTime? day)
        {
            return View(utils.CreateListViewModel(day));
        }

        public void ChangeDay(DateTime? day)
        {
            if (day.HasValue)
                utils.CurrentDay = day.Value;
        }

        public async Task<IActionResult> Details(string id)
        {
            AlertModel alert = await utils.Get(id);

            if (alert != null)
                return View(alert);
            else
                return View("Error");
        }

        public async Task<IActionResult> SystemDetails(string systemName)
        {
            SystemStatusModel status = await utils.GetSystemStatus(systemName);

            if (status != null)
                return View(status);
            else
                return View("Error");
        }

        public async Task<GenericActionResult> CloseAlert(string id)
        {
            return await utils.CloseAlert(id);
        }

        public async Task<GenericActionResult> CloseAllAlerts()
        {
            return await utils.CloseAll();
        }

        public IActionResult PnlTableViewComponent()
        {
            return ViewComponent("PnlTable", new { day = utils.CurrentDay });
        }

        public IActionResult SystemsListViewComponent()
        {
            return ViewComponent("SystemsList");
        }

        public IActionResult RefreshOpenAlerts()
        {
            return ViewComponent("AlertsList", new { listType = AlertsListType.Open, day = utils.CurrentDay });
        }

        public IActionResult RefreshClosedAlerts()
        {
            return ViewComponent("AlertsList", new { listType = AlertsListType.Closed, day = utils.CurrentDay });
        }

        public IActionResult RefreshActivityStats()
        {
            return ViewComponent("ActivityStats");
        }
    }
}

StratedgemeMonitor/Controllers/Orders/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StratedgemeMonitor.Models.Orders;
using System;
using System.Threading.Tasks;

namespace StratedgemeMonitor.Controllers.Orders
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly OrdersControllerUtils utils;

        public OrdersController(OrdersControllerUtils utils)
        {
            this.utils = utils;
        }

        public async Task<IActionResult> Index(DateTime? day)
        {
            return View(await utils.CreateListViewModel(day));
        }

        public async Task<IActionResult> Details(long id)
        {
            OrderModel order = await utils.GetByPermanentId(id);

            if (order != null)
                return View(order);
            else
                return View("Error");
        }

        public async Task<FileResult> ExportExcel()
        {
            return await utils.ExportExcel();
        }
    }
}

StratedgemeMonitor/Views/Shared/AlertPartial.cshtml
@using static Capital.GSG.FX.Data.Core.SystemData.AlertLevel;
@using static Capital.GSG.FX.Data.Core.SystemData.AlertStatus;

@model StratedgemeMonitor.Models.Alerts.AlertModel

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.AlertId)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.AlertId)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Timestamp)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Timestamp)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Source)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Source)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Subject)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Subject)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Body)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Body)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Level)
    </dt>
    <dd class="@(Model.Level <= INFO ? "text-success" : Model.Level <= WARNING ? "text-warning" : "text-danger")">
        @Html.DisplayFor(model => model.Level)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Status)
    </dt>
    <dd class="@(Model.Status == CLOSED ? "text-success" : "text-danger")">
        @Html.DisplayFor(model => model.Status)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.ClosedTimestamp)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.ClosedTimestamp)
    </dd>
</dl>

StratedgemeMonitor/Views/Shared/FXEventPartial.cshtml
@using static Capital.GSG.FX.Data.Core.MarketData.FXEventLevel

@model StratedgemeMonitor.Models.FXEvents.FXEventModel
        
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Currency)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Currency)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Timestamp)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Timestamp)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Level)
    </dt>
    <dd class="@(Model.Level == LOW ? "text-success" : Model.Level == MEDIUM ? "text-warning" : Model.Level == HIGH ? "text-danger" : "")">
        @Html.DisplayFor(model => model.Level)
    </dd>
</dl>
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Actual)
    </dt>
    <dd class="text-danger">
        @Html.DisplayFor(model => model.Actual)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Forecast)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Forecast)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Previous)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Previous)
    </dd>
</dl>
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Explanation)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Explanation)
    </dd>
</dl>

StratedgemeMonitor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@ViewData["Title"] - Stratedge.me Monitor</title>

    <link rel="icon" href="~/images/favicon.png" />

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="~/lib/bootstrap-toggle/css/bootstrap-toggle.css" rel="stylesheet" />
        <link href="~/lib/syncfusion-javascript/Content/ej/web/bootstrap-theme/ej.web.all.min.css" rel="stylesheet" />
        <link href="~/lib/syncfusion-javascript/Content/ej/web/responsive-css/ej.responsive.css" rel="stylesheet" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.syncfusion.com/14.3.0.49/js/web/bootstrap-theme/ej.web.all.min.css"
              asp-fallback-href="~/lib/syncfusion-javascript/Content/ej/web/bootstrap-theme/ej.web.all.min.css"
              asp-fallback-test-class="ejinputtext" asp-fallback-test-property="border-radius" asp-fallback-test-value="4px" />
        <link rel="stylesheet" href="https://cdn.syncfusion.com/14.3.0.49/js/web/responsive-css/ej.responsive.css"
              asp-fallback-href="~/lib/syncfusion-javascript/Content/ej/web/responsive-css/ej.responsive.css"
              asp-fallback-test-class="ejinputtext" asp-fallback-test-property="border-radius" asp-fallback-test-value="4px" />
    </environment>

    <link rel="stylesheet" href="~/css/site.css" />
</head>

@await FlushAsync()

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Alerts" asp-action="Index" class="navbar-brand">
                <img src="~/images/LogoGSG_300x893_transparent_bg.png" alt="GSG" />
            </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a asp-area="" asp-controller="Alerts" asp-action="Index">Alerts</a></li>
                <li><a asp-area="" asp-controller="Positions" asp-action="Index">Positions</a></li>
                <li><a asp-area="" asp-controller="Orders" asp-action="Index">Orders</a></li>
                <li><a asp-area="" asp-controller="Executions" asp-action="Index">Trades</a></li>
                <li><a asp-area="" asp-controller="FXEvents" asp-action="Index">FX Events</a></li>
                <li><a asp-area="" asp-controller="NewsBulletins" asp-action="Index">News Bulletins</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Clients <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a asp-area="" asp-controller="FAConfigurations" asp-action="Index">IB Allocations</a></li>
                    </ul>
                </li>
                <li class="dropdown hidden-sm hidden-xs">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">IB <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a asp-area="" asp-controller="IBFutureContracts" asp-action="Index">Futures</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Systems <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a asp-area="" asp-controller="Strategies" asp-action="Index">Strategies</a></li>
                        <li><a asp-area="" asp-controller="TradeEngine" asp-action="Index">Trade Engines</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a asp-area="" asp-controller="DBLogger" asp-action="Index">DB Loggers</a></li>
                        <li><a asp-area="" asp-controller="MonitorBackend" asp-action="Index">Monitor Backend</a></li>
                    </ul>
                </li>
            </ul>
            @await Html.PartialAsync("_LoginPartial")
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <footer>
            <p>&copy; 2016-@DateTime.Today.Year GSG Limited</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/tether/dist/js/tether.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/site-alerts.js"></script>
        <script src="~/js/site-systems.js"></script>
        <script src="~/js/site-tradeengines.js"></script>
        <script src="~/lib/jquery-easing/jquery.easing.js"></script>
        <script src="~/lib/jsrender/jsrender.js"></script>
        <script src="~/lib/syncfusion-javascript/Scripts/ej/web/ej.web.all.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/bootstrap-toggle/js/bootstrap-toggle.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
        <script src="https://cdn.syncfusion.com/js/assets/external/jquery.easing.1.3.min.js"
                asp-fallback-src="~/lib/jquery-easing/jquery.easing.js"
                asp-fallback-test="window.jQuery.easing.jswing"></script>
        <script src="https://cdn.syncfusion.com/js/assets/external/jsrender.js"
                asp-fallback-src="~/lib/jsrender/jsrender.js"
                asp-fallback-test="window.ej"></script>
        <script src="https://cdn.syncfusion.com/14.3.0.49/js/web/ej.web.all.min.js"
                asp-fallback-src="~/lib/syncfusion-javascript/Scripts/ej/web/ej.web.all.min.js"
                asp-fallback-test="window.ej"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>
<ej-script-manager></ej-script-manager>